// apps/web/src/client/pages/Login.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { useI18n } from 'vue-i18n';
import { useAuth } from '../composables/useAuth';

const { t } = useI18n();
const router = useRouter();
const route = useRoute();
const { login, isAuthenticated, isBootstrapLoading, isInitialized } = useAuth();

const username = ref('');
const password = ref('');
const error = ref<string | null>(null);

async function handleSubmit(e: Event) {
  e.preventDefault();
  error.value = null;
  try {
    await login({ username: username.value, password: password.value });
    const redirect = (route.query.redirect as string) || '/';
    router.replace(redirect);
  } catch (err: unknown) {
    if (err instanceof Error) {
      error.value = err.message || t('auth.loginError');
    } else {
      error.value = t('auth.loginError');
    }
  }
}
</script>

<template>
  <div v-if="isBootstrapLoading" class="loading-screen">{{ t('dashboard.loading') }}</div>
  <div v-else-if="!isInitialized" />
  <div v-else-if="isAuthenticated" />
  <div v-else class="login-container prompthub-web-auth">
    <div class="login-card rounded-[28px] border border-slate-200/80 bg-white/95 p-8 shadow-[0_32px_90px_rgba(15,23,42,0.10)] backdrop-blur">
      <h2 class="login-title text-3xl font-semibold text-slate-900">
        {{ t('auth.loginTitle') }}
      </h2>
      <p class="setup-hint">
        {{ t('auth.loginDescription') }}
      </p>

      <div v-if="error" class="login-error">{{ error }}</div>

      <form @submit="handleSubmit" class="login-form">
        <div class="form-group">
          <label for="username" class="text-sm font-semibold text-slate-700">
            {{ t('auth.username') }}
          </label>
          <input
            id="username"
            v-model="username"
            type="text"
            required
            class="web-auth-input"
          />
        </div>

        <div class="form-group">
          <label for="password" class="text-sm font-semibold text-slate-700">
            {{ t('auth.password') }}
          </label>
          <input
            id="password"
            v-model="password"
            type="password"
            required
            class="web-auth-input"
          />
        </div>

        <button type="submit" class="login-submit web-auth-submit">
          <span class="text-white">{{ t('auth.signIn') }}</span>
        </button>
      </form>

      <div class="auth-inline-actions auth-inline-actions-column">
        <span class="setup-hint">{{ t('auth.needAccount') }}</span>
        <router-link to="/register" class="auth-link-button auth-link-button-block">
          {{ t('auth.register') }}
        </router-link>
      </div>
    </div>
  </div>
</template>

// apps/web/src/client/pages/Login.tsx
import React, { useState } from 'react';
import { useNavigate, useLocation, Navigate, Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../contexts/AuthContext';

export function LoginPage() {
  const { t } = useTranslation();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const {
    login,
    isAuthenticated,
    isBootstrapLoading,
    isInitialized,
  } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();

  const state = location.state as { from?: { pathname?: string } } | null;
  const from = state?.from?.pathname || '/';

  if (isBootstrapLoading) {
    return <div className="loading-screen">{t('dashboard.loading')}</div>;
  }

  if (!isInitialized) {
    return <Navigate to="/setup" replace />;
  }

  if (isAuthenticated) {
    return <Navigate to={from} replace />;
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    try {
      await login({ username, password });
      navigate(from, { replace: true });
    } catch (err: unknown) {
      if (err instanceof Error) {
        setError(err.message || t('auth.loginError'));
      } else {
        setError(t('auth.loginError'));
      }
    }
  };

  return (
    <div className="login-container prompthub-web-auth">
      <div className="login-card rounded-[28px] border border-slate-200/80 bg-white/95 p-8 shadow-[0_32px_90px_rgba(15,23,42,0.10)] backdrop-blur">
        <h2 className="login-title text-3xl font-semibold text-slate-900">
          {t('auth.loginTitle')}
        </h2>
        <p className="setup-hint">
          {t('auth.loginDescription')}
        </p>

        {error && <div className="login-error">{error}</div>}

        <form onSubmit={handleSubmit} className="login-form">
          <div className="form-group">
            <label htmlFor="username" className="text-sm font-semibold text-slate-700">
              {t('auth.username')}
            </label>
            <input
              id="username"
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
              className="web-auth-input"
            />
          </div>

          <div className="form-group">
            <label htmlFor="password" className="text-sm font-semibold text-slate-700">
              {t('auth.password')}
            </label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              className="web-auth-input"
            />
          </div>

          <button type="submit" className="login-submit web-auth-submit">
            <span className="text-white">{t('auth.signIn')}</span>
          </button>
        </form>

        <div className="auth-inline-actions auth-inline-actions-column">
          <span className="setup-hint">{t('auth.needAccount')}</span>
          <Link to="/register" className="auth-link-button auth-link-button-block">
            {t('auth.register')}
          </Link>
        </div>
      </div>
    </div>
  );
}
